# Dependencies
markdown: kramdown
# markdown: redcarpet
highlighter: pygments
lsi: true
safe: true
auto: true

encoding: utf-8

# Permalinks
# permalink: pretty
permalink: /:title.html

comments: disqus

# Personal Config
title: "Nathan Lui's blog"
url: http://NathanLvzs.github.io
baseurl: /
github: https://github.com/NathanLvzs
repo: https://github.com/NathanLvzs/NathanLvzs.github.io
author:
  name: 'Nathan Lui'
  #url: https://twitter.com/blabla


seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
