# Dependencies
markdown: kramdown
# markdown: redcarpet
highlighter: rouge
# highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
lsi: false
# safe: true

encoding: utf-8
timezone: Asia/Chongqing

# permalink: pretty
# permalink: /blog/:title.html
permalink: /:title.html

# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap

# comments :
#   provider : duoshuo
#   duoshuo :
#     short_name : nathan

# Personal Config
title: NathanLVZS
url: http://nathanlvzs.github.io
twitter: https://twitter.com/NathanLZS
github: https://github.com/NathanLvzs
linkedin: https://www.linkedin.com/in/lvzishen
weibo: http://weibo.com/destinylzs
# baseurl: /#default is "", means the root
author:
  name: NathanLVZS
  nickname: Nathan
  email: lvzshen@outlook.com
  site: http://nathanlvzs.github.io

# seo: 
#   keyword: 
#   description: 
# config:
#   js_dir:
#   img_dir:
#   css_dir:
